qa:
    dynamoDbName: TBC
    dynamoDBPrimaryKey : {'stage': 'Prod'}
    generateBillingURL:
    billingBucketName: prebilling-aws-qa-mc
    prefixBillingSummaryFileName: aws_summary_MC_
    prefixBillingClientFileName: aws_client_MC_
    prefixBillingDetailFileName: aws_detail_MC_
    generateBillingTimeoutSleep: 60
    LocalBillingFiles: /billingFiles/
    csvSummaryHeaders: ['ob', 'mpa', 'accountIdCsb', 'subscriptionIdCsb', 'accountId', 'accountName', 'currency', 'exchangeRate', 'priceFactor', 'rebateFactor', 'charge', 'chargeVendor', 'rebateVendor', 'invoiceDate', 'chargeRef', 'chargeVendorRef', 'margin', 'rebateVendorRef', 'currencyRef']
    csvClientHeaders: ['chargeType', 'region', 'service', 'resourceName', 'resourceId', 'price', 'quantity', 'unit', 'charge', 'currency', 'startDate', 'endDate', 'invoiceDate']
    csvDetailHeaders: ['ob', 'mpa', 'accountIdCsb', 'subscriptionIdCsb', 'accountId', 'chargeType', 'region', 'service', 'resourceName', 'resourceId', 'price', 'quantity', 'unit', 'charge', 'currency', 'startDate', 'endDate', 'invoiceDate', 'priceRef', 'chargeRef', 'currencyRef', 'reservationStartTime', 'reservationEndTime', 'reservationTotalReservedUnits', 'reservationUnusedQuantity']
    adminAccessKey:
    adminSecretKey:
    region: us-east-2
    awsApiHost:
    csbAccessKey:
    csbSecretKey:

dev:
    dynamoDbName: mc-azure-plan-INT-AR-azureDataTable-1WXYBXFDNG11I
    dynamoDBPrimaryKey : { 'configId': 'current'}
    generateBillingURL: https://gvqzlmv99i.execute-api.us-east-2.amazonaws.com/Prod/generateBilling
    generateCurrentBillingURL: https://gvqzlmv99i.execute-api.us-east-2.amazonaws.com/Prod/generateCurrentBillingCycle
    billingBucketName: prebilling-azure-plan-int-ar
    prefixBillingSummaryFileName: azure_summary_AR_
    prefixBillingDetailFileName: azure_detail_AR_
    prefixBillingSubSummaryFileName: azure_subsummary_AR_
    prefixBillingSubDetailFileName: azure_subdetail_AR_
    OB: AR
    consumptionFileName: AR_azure_consumption
    generateBillingTimeoutSleep: 1
    offset_a: 0
    offset_b: 3
    offset_menor: -1
    newPriceFactor: 97
    invalidPriceFactor: invalid
    LocalBillingFiles: /billingFiles/
    # variables para restaurar valores en la tabla de configuración de DynamoDB
    old_lang: ES
    old_bucketName: bucket
    old_priceFactor: 1
    # csvSummaryHeaders: ['ob', 'mpa', 'accountIdCsb', 'subscriptionIdCsb', 'accountId', 'accountName', 'currency', 'exchangeRate', 'priceFactor', 'rebateFactor', 'charge', 'chargeVendor', 'rebateVendor', 'invoiceDate', 'chargeRef', 'chargeVendorRef', 'margin', 'rebateVendorRef', 'currencyRef']
    csvSummaryHeaders: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId', 'customerName', 'domain', 'currency', 'priceFactor', 'priceFactorRI', 'priceFactorSW', 'priceFactorMP', 'charge', 'chargeVendor', 'invoiceDate', 'chargeRef', 'chargeVendorRef', 'margin', 'currencyRef', 'exchangeRate']
    csvSubSummaryHeaders: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId', 'customerName', 'domain', 'subsubscriptionId', 'subsubscriptionName', 'currency', 'priceFactor', 'priceFactorRI', 'priceFactorSW', 'priceFactorMP', 'charge', 'chargeVendor', 'invoiceDate', 'chargeRef', 'chargeVendorRef', 'margin', 'currencyRef', 'exchangeRate']
    csvDetailHeaders: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId', 'chargeType', 'region', 'service', 'resourceName', 'resourceId', 'price', 'quantity', 'unit', 'charge', 'currency', 'startDate', 'endDate', 'invoiceDate', 'exchangeRate', 'partnerDiscount', 'customerDiscount', 'billingFrequency']
    csvSubDetailHeaders: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId', 'subsubscriptionId', 'subsubscriptionName', 'chargeType', 'region', 'service', 'resourceName', 'resourceId', 'price', 'quantity', 'unit', 'charge', 'currency', 'startDate', 'endDate', 'invoiceDate', 'priceRef', 'chargeRef', 'currencyRef', 'exchangeRate', 'partnerDiscount', 'customerDiscount']
    
    csvCurrentBillingSummaryHeaders: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId','customerName', 'domain', 'charge', 'currency','chargeRef', 'chargeRef', 'exchangeRate']
    csvCurrentBillingDetaillHeaders: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId', 'service', 'resourceName', 'resourceId', 'quantity', 'unit', 'charge', 'currency', 'exchangeRate', 'chargeRef', 'currencyRef']
    csvCurrentBillingDetaillHeadersRefFalse: ['ob', 'accountIdCsb', 'subscriptionIdCsb', 'customerId', 'subscriptionId', 'service', 'resourceName', 'resourceId', 'quantity', 'unit', 'charge', 'currency']
    adminAccessKey: AKIAZEVGJQRQWQK7KMGS
    adminSecretKey: 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
    region: us-east-2
    awsApiHost: gvqzlmv99i.execute-api.us-east-2.amazonaws.com
    csbAccessKey:
    csbSecretKey:
    ms_client_id: 
    ms_client_secret:
    